/**
 * @fileoverview Mandatory Legal Notices & Disclaimers
 * This text MUST appear on all AI-generated outputs (Screens, SVGs, Reports).
 */

export const LEGAL_DISCLAIMERS = {
    CONCEPT_ONLY: {
        short: "CONCEPT ONLY - NOT FOR CONSTRUCTION",
        long: "This design is a conceptual layout generated by AI. It is NOT a certified engineering drawing or structural plan. Use for visualization only."
    },
    CONSULT_PROFESSIONAL: {
        text: "Always verify dimensions and structural feasibility with a licensed architect or civil engineer before proceeding."
    },
    NO_LIABILITY: {
        text: "The platform assumes no liability for errors, omissions, or regulatory non-compliance in this generated concept."
    }
};

export function getWatermarkSVG(width, height) {
    return `
        <text x="${width / 2}" y="${height / 2}" 
              transform="rotate(-45, ${width / 2}, ${height / 2})" 
              font-size="${width / 10}" 
              fill="rgba(255,0,0,0.1)" 
              text-anchor="middle" 
              font-family="Arial">
            AI GENERATED CONCEPT
        </text>
    `;
}
